// autogenerated at 2021-07-04T08:47:55.747Z by: npm run dev
// use app.leaf.tags["mix"] = LaravelMixLeafTag()
// or app.registerLaravelMix()
// in configure.swift
// then you can use 
// <link href='#mix("/css/app.css")' rel='stylesheet'>
// <script src='#mix("/js/app.js")' defer></script>
// in your leaf templates

import Vapor
import Leaf

public struct LaravelMixAssets {
    // probably the version should be md5 of the mix-manifest.json
    // and be reloaded every new build on each request or not?
    // this is to avoid rebuilding the server on js file changes
    // maybe using https://github.com/cespare/reflex to reload
    // the server each time a swift file is modified. 
    public static var version: String = "2021-07-04T08:47:55.747Z"
    public static var files: [String: String] = [
        "/js/app.js": "/js/app.js?id=a16a8bd77fb60f120543",
        "/css/app.css": "/css/app.css?id=d41d8cd98f00b204e980",
    ]
    
    public static func get(_ file:String) -> String? {
        return LaravelMixAssets.files[file]
    }
}

struct LaravelMixLeafTagError: Error {}

public struct LaravelMixLeafTag: LeafTag {
    
    public init() {}
    
    public func render(_ ctx: LeafContext) throws -> LeafData {
        
        if (ctx.parameters.count <= 0) {
            throw LaravelMixLeafTagError()
        }

        guard let file = ctx.parameters[0].string else {
                throw LaravelMixLeafTagError()
        }

        return LeafData.string(LaravelMixAssets.files[file])
    }
}

extension Application {
    
    public func registerLaravelMix() {
        self.leaf.tags["mix"] = LaravelMixLeafTag()
    }
}
